# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

target "HermitWeekend" do
  # React Native pods
  pod "React", :path => "../node_modules/react-native/"
  pod "React-Core", :path => "../node_modules/react-native/"
end
